#ifndef _TACTILE_SWITCH_PRIVATE_H_ 
#define _TACTILE_SWITCH_PRIVATE_H_   

/*******************************************************/
/********************** NEW TYPE ***********************/
/*******************************************************/
typedef union
    {
	u16 Tactile_Switches;
	struct
	    {
		u16 Tactile_Switch_u8Switch1 :1;
		u16 Tactile_Switch_u8Switch2 :1;
		u16 Tactile_Switch_u8Switch3 :1;
		u16 Tactile_Switch_u8Switch4 :1;
		u16 Tactile_Switch_u8Switch5 :1;
		u16 Tactile_Switch_u8Switch6 :1;
		u16 Tactile_Switch_u8Switch7 :1;
		u16 Tactile_Switch_u8Switch8 :1;
		u16 Tactile_Switch_u8Switch9 :1;
		u16 Tactile_Switch_u8Switch10 :1;
		u16 Tactile_Switch_u8Switch11 :1;
		u16 Tactile_Switch_u8Switch12 :1;
		u16 Tactile_Switch_u8Switch13 :1;
		u16 Tactile_Switch_u8Switch14 :1;
		u16 Tactile_Switch_u8Switch15 :1;
		u16 Tactile_Switch_u8Switch16 :1;
	    };
    } Tactile_Switch_u16Switches;

/*******************************************************/
/**************** Private Definitions ******************/
/*******************************************************/

/*Comment!: Initial Value For Switches as unPressed */
#define TACTILE_SWITCH_INITIAL_UNPRESSED   0
#define TACTILE_FLAG_INITIAL_DOWN          0
#define TACTILE_SWITCH_BOUNCING_FLAG_DOWN  0
#define TACTILE_SWITCH_FLAG_UP             1
#define TACTILE_SWITCH_COUNTER_LIMIT       1

/*******************************************************/
/*****************  Private Functions  *****************/
/*******************************************************/

/*Comment!: */
#define CLR_BIT(Reg,Bit_no)                   ((Reg)&=(~(1<<(Bit_no))))
#define GET_BIT(Reg,Bit_no)                   (((Reg)>>(Bit_no))&1)
#define SET_BIT(Reg,Bit_no)                   ((Reg)|=(1<<(Bit_no)))

/******************************************************/
/********************** Arrays ************************/
/******************************************************/

static Tactile_Switch_u16Switches Tactile_Switch_u16State;

static Tactile_Switch_u16Switches Tactile_Switch_u16Bouncing_Flag;

static u8 TACTILE_SWITCH_u8PIN_PRESSED_COUNTER_ARRAY[TACTILE_SWITCH_u8SWITCHES_NUM] =
    {
    0
    };

static u8 TACTILE_SWITCH_u8PIN_UNPRESSED_COUUNTER_ARRAY[TACTILE_SWITCH_u8SWITCHES_NUM] =
    {
    0
    };

#if TACTILE_SWITCH_u8SWITCHES_NUM==1

const u8 TACTILE_SWITCH_u8PIN_NUMBERS_ARRAY[TACTILE_SWITCH_u8SWITCHES_NUM] =
    {TACTILE_SWITCH_u8SWITCH1PIN};

const u8 TACTILE_SWITCH_u8PRESSED_STATE_ARRAY[TACTILE_SWITCH_u8SWITCHES_NUM] =
    {TACTILE_SWITCH_u8SWITCH1_PRESSED_STATE};

#elif TACTILE_SWITCH_u8SWITCHES_NUM==2

const u8 TACTILE_SWITCH_u8PIN_NUMBERS_ARRAY[TACTILE_SWITCH_u8SWITCHES_NUM] =
    {TACTILE_SWITCH_u8SWITCH1PIN,TACTILE_SWITCH_u8SWITCH2PIN};

const u8 TACTILE_SWITCH_u8PRESSED_STATE_ARRAY[TACTILE_SWITCH_u8SWITCHES_NUM] =
    {TACTILE_SWITCH_u8SWITCH1_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH2_PRESSED_STATE};

#elif TACTILE_SWITCH_u8SWITCHES_NUM==3

const u8 TACTILE_SWITCH_u8PIN_NUMBERS_ARRAY[TACTILE_SWITCH_u8SWITCHES_NUM] =
    {TACTILE_SWITCH_u8SWITCH1PIN,TACTILE_SWITCH_u8SWITCH2PIN ,TACTILE_SWITCH_u8SWITCH3PIN};

const u8 TACTILE_SWITCH_u8PRESSED_STATE_ARRAY[TACTILE_SWITCH_u8SWITCHES_NUM] =
    {TACTILE_SWITCH_u8SWITCH1_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH2_PRESSED_STATE ,TACTILE_SWITCH_u8SWITCH3_PRESSED_STATE};

#elif TACTILE_SWITCH_u8SWITCHES_NUM==4

const u8 TACTILE_SWITCH_u8PIN_NUMBERS_ARRAY[TACTILE_SWITCH_u8SWITCHES_NUM] =
    {TACTILE_SWITCH_u8SWITCH1PIN,TACTILE_SWITCH_u8SWITCH2PIN,TACTILE_SWITCH_u8SWITCH3PIN,TACTILE_SWITCH_u8SWITCH4PIN};

const u8 TACTILE_SWITCH_u8PRESSED_STATE_ARRAY[TACTILE_SWITCH_u8SWITCHES_NUM] =
    {TACTILE_SWITCH_u8SWITCH1_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH2_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH3_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH4_PRESSED_STATE};

#elif TACTILE_SWITCH_u8SWITCHES_NUM==5

const u8 TACTILE_SWITCH_u8PIN_NUMBERS_ARRAY[TACTILE_SWITCH_u8SWITCHES_NUM] =
    {TACTILE_SWITCH_u8SWITCH1PIN,TACTILE_SWITCH_u8SWITCH2PIN,TACTILE_SWITCH_u8SWITCH3PIN,TACTILE_SWITCH_u8SWITCH4PIN
    ,TACTILE_SWITCH_u8SWITCH5PIN};

const u8 TACTILE_SWITCH_u8PRESSED_STATE_ARRAY[TACTILE_SWITCH_u8SWITCHES_NUM] =
    {TACTILE_SWITCH_u8SWITCH1_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH2_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH3_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH4_PRESSED_STATE
    ,TACTILE_SWITCH_u8SWITCH5_PRESSED_STATE};

#elif TACTILE_SWITCH_u8SWITCHES_NUM==6

const u8 TACTILE_SWITCH_u8PIN_NUMBERS_ARRAY[TACTILE_SWITCH_u8SWITCHES_NUM] =
    {TACTILE_SWITCH_u8SWITCH1PIN,TACTILE_SWITCH_u8SWITCH2PIN,TACTILE_SWITCH_u8SWITCH3PIN,TACTILE_SWITCH_u8SWITCH4PIN
    ,TACTILE_SWITCH_u8SWITCH5PIN,TACTILE_SWITCH_u8SWITCH6PIN};

const u8 TACTILE_SWITCH_u8PRESSED_STATE_ARRAY[TACTILE_SWITCH_u8SWITCHES_NUM] =
    {TACTILE_SWITCH_u8SWITCH1_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH2_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH3_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH4_PRESSED_STATE
    ,TACTILE_SWITCH_u8SWITCH5_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH6_PRESSED_STATE};

#elif TACTILE_SWITCH_u8SWITCHES_NUM==7

const u8 TACTILE_SWITCH_u8PIN_NUMBERS_ARRAY[TACTILE_SWITCH_u8SWITCHES_NUM] =
    {TACTILE_SWITCH_u8SWITCH1PIN,TACTILE_SWITCH_u8SWITCH2PIN,TACTILE_SWITCH_u8SWITCH3PIN,TACTILE_SWITCH_u8SWITCH4PIN
    ,TACTILE_SWITCH_u8SWITCH5PIN,TACTILE_SWITCH_u8SWITCH6PIN,TACTILE_SWITCH_u8SWITCH7PIN};

const u8 TACTILE_SWITCH_u8PRESSED_STATE_ARRAY[TACTILE_SWITCH_u8SWITCHES_NUM] =
    {TACTILE_SWITCH_u8SWITCH1_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH2_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH3_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH4_PRESSED_STATE
    ,TACTILE_SWITCH_u8SWITCH5_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH6_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH7_PRESSED_STATE};

#elif TACTILE_SWITCH_u8SWITCHES_NUM==8

const u8 TACTILE_SWITCH_u8PIN_NUMBERS_ARRAY[TACTILE_SWITCH_u8SWITCHES_NUM] =
    {TACTILE_SWITCH_u8SWITCH1PIN,TACTILE_SWITCH_u8SWITCH2PIN,TACTILE_SWITCH_u8SWITCH3PIN,TACTILE_SWITCH_u8SWITCH4PIN
    ,TACTILE_SWITCH_u8SWITCH5PIN,TACTILE_SWITCH_u8SWITCH6PIN,TACTILE_SWITCH_u8SWITCH7PIN,TACTILE_SWITCH_u8SWITCH8PIN};

const u8 TACTILE_SWITCH_u8PRESSED_STATE_ARRAY[TACTILE_SWITCH_u8SWITCHES_NUM] =
    {TACTILE_SWITCH_u8SWITCH1_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH2_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH3_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH4_PRESSED_STATE
    ,TACTILE_SWITCH_u8SWITCH5_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH6_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH7_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH8_PRESSED_STATE};

#elif TACTILE_SWITCH_u8SWITCHES_NUM==9

const u8 TACTILE_SWITCH_u8PIN_NUMBERS_ARRAY[TACTILE_SWITCH_u8SWITCHES_NUM] =
    {TACTILE_SWITCH_u8SWITCH1PIN,TACTILE_SWITCH_u8SWITCH2PIN,TACTILE_SWITCH_u8SWITCH3PIN,TACTILE_SWITCH_u8SWITCH4PIN
    ,TACTILE_SWITCH_u8SWITCH5PIN,TACTILE_SWITCH_u8SWITCH6PIN,TACTILE_SWITCH_u8SWITCH7PIN,TACTILE_SWITCH_u8SWITCH8PIN
    ,TACTILE_SWITCH_u8SWITCH9PIN};

const u8 TACTILE_SWITCH_u8PRESSED_STATE_ARRAY[TACTILE_SWITCH_u8SWITCHES_NUM] =
    {TACTILE_SWITCH_u8SWITCH1_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH2_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH3_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH4_PRESSED_STATE
    ,TACTILE_SWITCH_u8SWITCH5_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH6_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH7_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH8_PRESSED_STATE
    ,TACTILE_SWITCH_u8SWITCH9_PRESSED_STATE};

#elif TACTILE_SWITCH_u8SWITCHES_NUM==10

const u8 TACTILE_SWITCH_u8PIN_NUMBERS_ARRAY[TACTILE_SWITCH_u8SWITCHES_NUM] =
    {TACTILE_SWITCH_u8SWITCH1PIN,TACTILE_SWITCH_u8SWITCH2PIN,TACTILE_SWITCH_u8SWITCH3PIN,TACTILE_SWITCH_u8SWITCH4PIN
    ,TACTILE_SWITCH_u8SWITCH5PIN,TACTILE_SWITCH_u8SWITCH6PIN,TACTILE_SWITCH_u8SWITCH7PIN,TACTILE_SWITCH_u8SWITCH8PIN
    ,TACTILE_SWITCH_u8SWITCH9PIN,TACTILE_SWITCH_u8SWITCH10PIN};

const u8 TACTILE_SWITCH_u8PRESSED_STATE_ARRAY[TACTILE_SWITCH_u8SWITCHES_NUM] =
    {TACTILE_SWITCH_u8SWITCH1_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH2_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH3_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH4_PRESSED_STATE
    ,TACTILE_SWITCH_u8SWITCH5_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH6_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH7_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH8_PRESSED_STATE
    ,TACTILE_SWITCH_u8SWITCH9_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH10_PRESSED_STATE};

#elif TACTILE_SWITCH_u8SWITCHES_NUM==11

const u8 TACTILE_SWITCH_u8PIN_NUMBERS_ARRAY[TACTILE_SWITCH_u8SWITCHES_NUM] =
    {TACTILE_SWITCH_u8SWITCH1PIN,TACTILE_SWITCH_u8SWITCH2PIN,TACTILE_SWITCH_u8SWITCH3PIN,TACTILE_SWITCH_u8SWITCH4PIN
    ,TACTILE_SWITCH_u8SWITCH5PIN,TACTILE_SWITCH_u8SWITCH6PIN,TACTILE_SWITCH_u8SWITCH7PIN,TACTILE_SWITCH_u8SWITCH8PIN
    ,TACTILE_SWITCH_u8SWITCH9PIN,TACTILE_SWITCH_u8SWITCH10PIN,TACTILE_SWITCH_u8SWITCH11PIN};

const u8 TACTILE_SWITCH_u8PRESSED_STATE_ARRAY[TACTILE_SWITCH_u8SWITCHES_NUM] =
    {TACTILE_SWITCH_u8SWITCH1_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH2_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH3_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH4_PRESSED_STATE
    ,TACTILE_SWITCH_u8SWITCH5_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH6_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH7_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH8_PRESSED_STATE
    ,TACTILE_SWITCH_u8SWITCH9_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH10_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH11_PRESSED_STATE};

#elif TACTILE_SWITCH_u8SWITCHES_NUM==12

const u8 TACTILE_SWITCH_u8PIN_NUMBERS_ARRAY[TACTILE_SWITCH_u8SWITCHES_NUM] =
    {TACTILE_SWITCH_u8SWITCH1PIN,TACTILE_SWITCH_u8SWITCH2PIN,TACTILE_SWITCH_u8SWITCH3PIN,TACTILE_SWITCH_u8SWITCH4PIN
    ,TACTILE_SWITCH_u8SWITCH5PIN,TACTILE_SWITCH_u8SWITCH6PIN,TACTILE_SWITCH_u8SWITCH7PIN,TACTILE_SWITCH_u8SWITCH8PIN
    ,TACTILE_SWITCH_u8SWITCH9PIN,TACTILE_SWITCH_u8SWITCH10PIN,TACTILE_SWITCH_u8SWITCH11PIN,TACTILE_SWITCH_u8SWITCH12PIN};

const u8 TACTILE_SWITCH_u8PRESSED_STATE_ARRAY[TACTILE_SWITCH_u8SWITCHES_NUM] =
    {TACTILE_SWITCH_u8SWITCH1_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH2_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH3_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH4_PRESSED_STATE
    ,TACTILE_SWITCH_u8SWITCH5_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH6_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH7_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH8_PRESSED_STATE
    ,TACTILE_SWITCH_u8SWITCH9_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH10_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH11_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH12_PRESSED_STATE};

#elif TACTILE_SWITCH_u8SWITCHES_NUM==13

const u8 TACTILE_SWITCH_u8PIN_NUMBERS_ARRAY[TACTILE_SWITCH_u8SWITCHES_NUM] =
    {TACTILE_SWITCH_u8SWITCH1PIN,TACTILE_SWITCH_u8SWITCH2PIN,TACTILE_SWITCH_u8SWITCH3PIN,TACTILE_SWITCH_u8SWITCH4PIN
    ,TACTILE_SWITCH_u8SWITCH5PIN,TACTILE_SWITCH_u8SWITCH6PIN,TACTILE_SWITCH_u8SWITCH7PIN,TACTILE_SWITCH_u8SWITCH8PIN
    ,TACTILE_SWITCH_u8SWITCH9PIN,TACTILE_SWITCH_u8SWITCH10PIN,TACTILE_SWITCH_u8SWITCH11PIN,TACTILE_SWITCH_u8SWITCH12PIN
    ,TACTILE_SWITCH_u8SWITCH13PIN};

const u8 TACTILE_SWITCH_u8PRESSED_STATE_ARRAY[TACTILE_SWITCH_u8SWITCHES_NUM] =
    {TACTILE_SWITCH_u8SWITCH1_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH2_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH3_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH4_PRESSED_STATE
    ,TACTILE_SWITCH_u8SWITCH5_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH6_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH7_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH8_PRESSED_STATE
    ,TACTILE_SWITCH_u8SWITCH9_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH10_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH11_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH12_PRESSED_STATE
    ,TACTILE_SWITCH_u8SWITCH13_PRESSED_STATE};

#elif TACTILE_SWITCH_u8SWITCHES_NUM==14

const u8 TACTILE_SWITCH_u8PIN_NUMBERS_ARRAY[TACTILE_SWITCH_u8SWITCHES_NUM] =
    {TACTILE_SWITCH_u8SWITCH1PIN,TACTILE_SWITCH_u8SWITCH2PIN,TACTILE_SWITCH_u8SWITCH3PIN,TACTILE_SWITCH_u8SWITCH4PIN
    ,TACTILE_SWITCH_u8SWITCH5PIN,TACTILE_SWITCH_u8SWITCH6PIN,TACTILE_SWITCH_u8SWITCH7PIN,TACTILE_SWITCH_u8SWITCH8PIN
    ,TACTILE_SWITCH_u8SWITCH9PIN,TACTILE_SWITCH_u8SWITCH10PIN,TACTILE_SWITCH_u8SWITCH11PIN,TACTILE_SWITCH_u8SWITCH12PIN
    ,TACTILE_SWITCH_u8SWITCH13PIN,TACTILE_SWITCH_u8SWITCH14PIN};

const u8 TACTILE_SWITCH_u8PRESSED_STATE_ARRAY[TACTILE_SWITCH_u8SWITCHES_NUM] =
    {TACTILE_SWITCH_u8SWITCH1_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH2_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH3_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH4_PRESSED_STATE
    ,TACTILE_SWITCH_u8SWITCH5_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH6_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH7_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH8_PRESSED_STATE
    ,TACTILE_SWITCH_u8SWITCH9_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH10_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH11_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH12_PRESSED_STATE
    ,TACTILE_SWITCH_u8SWITCH13_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH14_PRESSED_STATE};

#elif TACTILE_SWITCH_u8SWITCHES_NUM==15

const u8 TACTILE_SWITCH_u8PIN_NUMBERS_ARRAY[TACTILE_SWITCH_u8SWITCHES_NUM] =
    {TACTILE_SWITCH_u8SWITCH1PIN,TACTILE_SWITCH_u8SWITCH2PIN,TACTILE_SWITCH_u8SWITCH3PIN,TACTILE_SWITCH_u8SWITCH4PIN
    ,TACTILE_SWITCH_u8SWITCH5PIN,TACTILE_SWITCH_u8SWITCH6PIN,TACTILE_SWITCH_u8SWITCH7PIN,TACTILE_SWITCH_u8SWITCH8PIN
    ,TACTILE_SWITCH_u8SWITCH9PIN,TACTILE_SWITCH_u8SWITCH10PIN,TACTILE_SWITCH_u8SWITCH11PIN,TACTILE_SWITCH_u8SWITCH12PIN
    ,TACTILE_SWITCH_u8SWITCH13PIN,TACTILE_SWITCH_u8SWITCH14PIN,TACTILE_SWITCH_u8SWITCH15PIN};

const u8 TACTILE_SWITCH_u8PRESSED_STATE_ARRAY[TACTILE_SWITCH_u8SWITCHES_NUM] =
    {TACTILE_SWITCH_u8SWITCH1_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH2_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH3_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH4_PRESSED_STATE
    ,TACTILE_SWITCH_u8SWITCH5_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH6_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH7_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH8_PRESSED_STATE
    ,TACTILE_SWITCH_u8SWITCH9_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH10_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH11_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH12_PRESSED_STATE
    ,TACTILE_SWITCH_u8SWITCH13_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH14_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH15_PRESSED_STATE};

#elif TACTILE_SWITCH_u8SWITCHES_NUM==16

const u8 TACTILE_SWITCH_u8PIN_NUMBERS_ARRAY[TACTILE_SWITCH_u8SWITCHES_NUM] =
    {TACTILE_SWITCH_u8SWITCH1PIN,TACTILE_SWITCH_u8SWITCH2PIN,TACTILE_SWITCH_u8SWITCH3PIN,TACTILE_SWITCH_u8SWITCH4PIN
    ,TACTILE_SWITCH_u8SWITCH5PIN,TACTILE_SWITCH_u8SWITCH6PIN,TACTILE_SWITCH_u8SWITCH7PIN,TACTILE_SWITCH_u8SWITCH8PIN
    ,TACTILE_SWITCH_u8SWITCH9PIN,TACTILE_SWITCH_u8SWITCH10PIN,TACTILE_SWITCH_u8SWITCH11PIN,TACTILE_SWITCH_u8SWITCH12PIN
    ,TACTILE_SWITCH_u8SWITCH13PIN,TACTILE_SWITCH_u8SWITCH14PIN,TACTILE_SWITCH_u8SWITCH15PIN,TACTILE_SWITCH_u8SWITCH16PIN};

const u8 TACTILE_SWITCH_u8PRESSED_STATE_ARRAY[TACTILE_SWITCH_u8SWITCHES_NUM] =
    {TACTILE_SWITCH_u8SWITCH1_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH2_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH3_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH4_PRESSED_STATE
    ,TACTILE_SWITCH_u8SWITCH5_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH6_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH7_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH8_PRESSED_STATE
    ,TACTILE_SWITCH_u8SWITCH9_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH10_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH11_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH12_PRESSED_STATE
    ,TACTILE_SWITCH_u8SWITCH13_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH14_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH15_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH16_PRESSED_STATE};

#else

#error  "TACTILE_SWITCH_u8SWITCHES_NUM is out of range"

#endif

#endif  
