#ifndef _TACTILE_SWITCH_CONFIG_H_ 
#define _TACTILE_SWITCH_CONFIG_H_ 

/*******************************************************/
/**************** Public Definitions *******************/
/*******************************************************/

/*Comment!: SWITCH PINS*/
/*Range!  : DIO_u8PIN0 ~ DIO_u8PIN31 */
#define TACTILE_SWITCH_u8SWITCH1PIN    DIO_u8PIN4
#define TACTILE_SWITCH_u8SWITCH2PIN    DIO_u8PIN1
#define TACTILE_SWITCH_u8SWITCH3PIN    DIO_u8PIN2
#define TACTILE_SWITCH_u8SWITCH4PIN    DIO_u8PIN3
#define TACTILE_SWITCH_u8SWITCH5PIN    DIO_u8PIN4
#define TACTILE_SWITCH_u8SWITCH6PIN    DIO_u8PIN5
#define TACTILE_SWITCH_u8SWITCH7PIN    DIO_u8PIN6
#define TACTILE_SWITCH_u8SWITCH8PIN    DIO_u8PIN7
#define TACTILE_SWITCH_u8SWITCH9PIN    DIO_u8PIN8
#define TACTILE_SWITCH_u8SWITCH10PIN   DIO_u8PIN9
#define TACTILE_SWITCH_u8SWITCH11PIN   DIO_u8PIN10
#define TACTILE_SWITCH_u8SWITCH12PIN   DIO_u8PIN11
#define TACTILE_SWITCH_u8SWITCH13PIN   DIO_u8PIN12
#define TACTILE_SWITCH_u8SWITCH14PIN   DIO_u8PIN13
#define TACTILE_SWITCH_u8SWITCH15PIN   DIO_u8PIN14
#define TACTILE_SWITCH_u8SWITCH16PIN   DIO_u8PIN15

/*Comment!: Number of Connected Switches*/
/*Range!  : 1 ~ 16 */
#define TACTILE_SWITCH_u8SWITCHES_NUM   1

/*Comment!: Output at Pressed State*/
/*Range!  : DIO_u8HIGH -DIO_u8LOW */
#define TACTILE_SWITCH_u8SWITCH1_PRESSED_STATE   DIO_u8HIGH
#define TACTILE_SWITCH_u8SWITCH2_PRESSED_STATE   DIO_u8LOW
#define TACTILE_SWITCH_u8SWITCH3_PRESSED_STATE   DIO_u8LOW
#define TACTILE_SWITCH_u8SWITCH4_PRESSED_STATE   DIO_u8LOW
#define TACTILE_SWITCH_u8SWITCH5_PRESSED_STATE   DIO_u8LOW
#define TACTILE_SWITCH_u8SWITCH6_PRESSED_STATE   DIO_u8LOW
#define TACTILE_SWITCH_u8SWITCH7_PRESSED_STATE   DIO_u8LOW
#define TACTILE_SWITCH_u8SWITCH8_PRESSED_STATE   DIO_u8LOW
#define TACTILE_SWITCH_u8SWITCH9_PRESSED_STATE   DIO_u8LOW
#define TACTILE_SWITCH_u8SWITCH10_PRESSED_STATE  DIO_u8LOW
#define TACTILE_SWITCH_u8SWITCH11_PRESSED_STATE  DIO_u8LOW
#define TACTILE_SWITCH_u8SWITCH12_PRESSED_STATE  DIO_u8LOW
#define TACTILE_SWITCH_u8SWITCH13_PRESSED_STATE  DIO_u8LOW
#define TACTILE_SWITCH_u8SWITCH14_PRESSED_STATE  DIO_u8LOW
#define TACTILE_SWITCH_u8SWITCH15_PRESSED_STATE  DIO_u8LOW
#define TACTILE_SWITCH_u8SWITCH16_PRESSED_STATE  DIO_u8LOW


#endif 
