#include"../../Shared_Libraries/types.h"
#include"../../MCAL_LAYER/DIO_DRIVER/DIO_interface.h"
#include"TACTILE_SWITCH_interface.h"  
#include"TACTILE_SWITCH_config.h" 
#include"TACTILE_SWITCH_private.h"

/******************************************************/
/********************** Arrays ************************/
/******************************************************/

static Tactile_Switch_u16Switches Tactile_Switch_u16State;

static Tactile_Switch_u16Switches Tactile_Switch_u16Bouncing_Flag;

static u8 TACTILE_SWITCH_u8PIN_PRESSED_COUNTER_ARRAY[TACTILE_SWITCH_u8SWITCHES_NUM] =
    {
    0
    };

static u8 TACTILE_SWITCH_u8PIN_UNPRESSED_COUUNTER_ARRAY[TACTILE_SWITCH_u8SWITCHES_NUM] =
    {
    0
    };

#if TACTILE_SWITCH_u8SWITCHES_NUM==1

const u8 TACTILE_SWITCH_u8PIN_NUMBERS_ARRAY[TACTILE_SWITCH_u8SWITCHES_NUM] =
    {TACTILE_SWITCH_u8SWITCH1PIN};

const u8 TACTILE_SWITCH_u8PRESSED_STATE_ARRAY[TACTILE_SWITCH_u8SWITCHES_NUM] =
    {TACTILE_SWITCH_u8SWITCH1_PRESSED_STATE};

#elif TACTILE_SWITCH_u8SWITCHES_NUM==2

const u8 TACTILE_SWITCH_u8PIN_NUMBERS_ARRAY[TACTILE_SWITCH_u8SWITCHES_NUM] =
    {TACTILE_SWITCH_u8SWITCH1PIN,TACTILE_SWITCH_u8SWITCH2PIN};

const u8 TACTILE_SWITCH_u8PRESSED_STATE_ARRAY[TACTILE_SWITCH_u8SWITCHES_NUM] =
    {TACTILE_SWITCH_u8SWITCH1_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH2_PRESSED_STATE};

#elif TACTILE_SWITCH_u8SWITCHES_NUM==3

const u8 TACTILE_SWITCH_u8PIN_NUMBERS_ARRAY[TACTILE_SWITCH_u8SWITCHES_NUM] =
    {TACTILE_SWITCH_u8SWITCH1PIN,TACTILE_SWITCH_u8SWITCH2PIN ,TACTILE_SWITCH_u8SWITCH3PIN};

const u8 TACTILE_SWITCH_u8PRESSED_STATE_ARRAY[TACTILE_SWITCH_u8SWITCHES_NUM] =
    {TACTILE_SWITCH_u8SWITCH1_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH2_PRESSED_STATE ,TACTILE_SWITCH_u8SWITCH3_PRESSED_STATE};

#elif TACTILE_SWITCH_u8SWITCHES_NUM==4

const u8 TACTILE_SWITCH_u8PIN_NUMBERS_ARRAY[TACTILE_SWITCH_u8SWITCHES_NUM] =
    {TACTILE_SWITCH_u8SWITCH1PIN,TACTILE_SWITCH_u8SWITCH2PIN,TACTILE_SWITCH_u8SWITCH3PIN,TACTILE_SWITCH_u8SWITCH4PIN};

const u8 TACTILE_SWITCH_u8PRESSED_STATE_ARRAY[TACTILE_SWITCH_u8SWITCHES_NUM] =
    {TACTILE_SWITCH_u8SWITCH1_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH2_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH3_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH4_PRESSED_STATE};

#elif TACTILE_SWITCH_u8SWITCHES_NUM==5

const u8 TACTILE_SWITCH_u8PIN_NUMBERS_ARRAY[TACTILE_SWITCH_u8SWITCHES_NUM] =
    {TACTILE_SWITCH_u8SWITCH1PIN,TACTILE_SWITCH_u8SWITCH2PIN,TACTILE_SWITCH_u8SWITCH3PIN,TACTILE_SWITCH_u8SWITCH4PIN
    ,TACTILE_SWITCH_u8SWITCH5PIN};

const u8 TACTILE_SWITCH_u8PRESSED_STATE_ARRAY[TACTILE_SWITCH_u8SWITCHES_NUM] =
    {TACTILE_SWITCH_u8SWITCH1_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH2_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH3_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH4_PRESSED_STATE
    ,TACTILE_SWITCH_u8SWITCH5_PRESSED_STATE};

#elif TACTILE_SWITCH_u8SWITCHES_NUM==6

const u8 TACTILE_SWITCH_u8PIN_NUMBERS_ARRAY[TACTILE_SWITCH_u8SWITCHES_NUM] =
    {TACTILE_SWITCH_u8SWITCH1PIN,TACTILE_SWITCH_u8SWITCH2PIN,TACTILE_SWITCH_u8SWITCH3PIN,TACTILE_SWITCH_u8SWITCH4PIN
    ,TACTILE_SWITCH_u8SWITCH5PIN,TACTILE_SWITCH_u8SWITCH6PIN};

const u8 TACTILE_SWITCH_u8PRESSED_STATE_ARRAY[TACTILE_SWITCH_u8SWITCHES_NUM] =
    {TACTILE_SWITCH_u8SWITCH1_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH2_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH3_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH4_PRESSED_STATE
    ,TACTILE_SWITCH_u8SWITCH5_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH6_PRESSED_STATE};

#elif TACTILE_SWITCH_u8SWITCHES_NUM==7

const u8 TACTILE_SWITCH_u8PIN_NUMBERS_ARRAY[TACTILE_SWITCH_u8SWITCHES_NUM] =
    {TACTILE_SWITCH_u8SWITCH1PIN,TACTILE_SWITCH_u8SWITCH2PIN,TACTILE_SWITCH_u8SWITCH3PIN,TACTILE_SWITCH_u8SWITCH4PIN
    ,TACTILE_SWITCH_u8SWITCH5PIN,TACTILE_SWITCH_u8SWITCH6PIN,TACTILE_SWITCH_u8SWITCH7PIN};

const u8 TACTILE_SWITCH_u8PRESSED_STATE_ARRAY[TACTILE_SWITCH_u8SWITCHES_NUM] =
    {TACTILE_SWITCH_u8SWITCH1_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH2_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH3_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH4_PRESSED_STATE
    ,TACTILE_SWITCH_u8SWITCH5_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH6_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH7_PRESSED_STATE};

#elif TACTILE_SWITCH_u8SWITCHES_NUM==8

const u8 TACTILE_SWITCH_u8PIN_NUMBERS_ARRAY[TACTILE_SWITCH_u8SWITCHES_NUM] =
    {TACTILE_SWITCH_u8SWITCH1PIN,TACTILE_SWITCH_u8SWITCH2PIN,TACTILE_SWITCH_u8SWITCH3PIN,TACTILE_SWITCH_u8SWITCH4PIN
    ,TACTILE_SWITCH_u8SWITCH5PIN,TACTILE_SWITCH_u8SWITCH6PIN,TACTILE_SWITCH_u8SWITCH7PIN,TACTILE_SWITCH_u8SWITCH8PIN};

const u8 TACTILE_SWITCH_u8PRESSED_STATE_ARRAY[TACTILE_SWITCH_u8SWITCHES_NUM] =
    {TACTILE_SWITCH_u8SWITCH1_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH2_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH3_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH4_PRESSED_STATE
    ,TACTILE_SWITCH_u8SWITCH5_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH6_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH7_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH8_PRESSED_STATE};

#elif TACTILE_SWITCH_u8SWITCHES_NUM==9

const u8 TACTILE_SWITCH_u8PIN_NUMBERS_ARRAY[TACTILE_SWITCH_u8SWITCHES_NUM] =
    {TACTILE_SWITCH_u8SWITCH1PIN,TACTILE_SWITCH_u8SWITCH2PIN,TACTILE_SWITCH_u8SWITCH3PIN,TACTILE_SWITCH_u8SWITCH4PIN
    ,TACTILE_SWITCH_u8SWITCH5PIN,TACTILE_SWITCH_u8SWITCH6PIN,TACTILE_SWITCH_u8SWITCH7PIN,TACTILE_SWITCH_u8SWITCH8PIN
    ,TACTILE_SWITCH_u8SWITCH9PIN};

const u8 TACTILE_SWITCH_u8PRESSED_STATE_ARRAY[TACTILE_SWITCH_u8SWITCHES_NUM] =
    {TACTILE_SWITCH_u8SWITCH1_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH2_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH3_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH4_PRESSED_STATE
    ,TACTILE_SWITCH_u8SWITCH5_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH6_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH7_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH8_PRESSED_STATE
    ,TACTILE_SWITCH_u8SWITCH9_PRESSED_STATE};

#elif TACTILE_SWITCH_u8SWITCHES_NUM==10

const u8 TACTILE_SWITCH_u8PIN_NUMBERS_ARRAY[TACTILE_SWITCH_u8SWITCHES_NUM] =
    {TACTILE_SWITCH_u8SWITCH1PIN,TACTILE_SWITCH_u8SWITCH2PIN,TACTILE_SWITCH_u8SWITCH3PIN,TACTILE_SWITCH_u8SWITCH4PIN
    ,TACTILE_SWITCH_u8SWITCH5PIN,TACTILE_SWITCH_u8SWITCH6PIN,TACTILE_SWITCH_u8SWITCH7PIN,TACTILE_SWITCH_u8SWITCH8PIN
    ,TACTILE_SWITCH_u8SWITCH9PIN,TACTILE_SWITCH_u8SWITCH10PIN};

const u8 TACTILE_SWITCH_u8PRESSED_STATE_ARRAY[TACTILE_SWITCH_u8SWITCHES_NUM] =
    {TACTILE_SWITCH_u8SWITCH1_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH2_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH3_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH4_PRESSED_STATE
    ,TACTILE_SWITCH_u8SWITCH5_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH6_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH7_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH8_PRESSED_STATE
    ,TACTILE_SWITCH_u8SWITCH9_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH10_PRESSED_STATE};

#elif TACTILE_SWITCH_u8SWITCHES_NUM==11

const u8 TACTILE_SWITCH_u8PIN_NUMBERS_ARRAY[TACTILE_SWITCH_u8SWITCHES_NUM] =
    {TACTILE_SWITCH_u8SWITCH1PIN,TACTILE_SWITCH_u8SWITCH2PIN,TACTILE_SWITCH_u8SWITCH3PIN,TACTILE_SWITCH_u8SWITCH4PIN
    ,TACTILE_SWITCH_u8SWITCH5PIN,TACTILE_SWITCH_u8SWITCH6PIN,TACTILE_SWITCH_u8SWITCH7PIN,TACTILE_SWITCH_u8SWITCH8PIN
    ,TACTILE_SWITCH_u8SWITCH9PIN,TACTILE_SWITCH_u8SWITCH10PIN,TACTILE_SWITCH_u8SWITCH11PIN};

const u8 TACTILE_SWITCH_u8PRESSED_STATE_ARRAY[TACTILE_SWITCH_u8SWITCHES_NUM] =
    {TACTILE_SWITCH_u8SWITCH1_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH2_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH3_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH4_PRESSED_STATE
    ,TACTILE_SWITCH_u8SWITCH5_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH6_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH7_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH8_PRESSED_STATE
    ,TACTILE_SWITCH_u8SWITCH9_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH10_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH11_PRESSED_STATE};

#elif TACTILE_SWITCH_u8SWITCHES_NUM==12

const u8 TACTILE_SWITCH_u8PIN_NUMBERS_ARRAY[TACTILE_SWITCH_u8SWITCHES_NUM] =
    {TACTILE_SWITCH_u8SWITCH1PIN,TACTILE_SWITCH_u8SWITCH2PIN,TACTILE_SWITCH_u8SWITCH3PIN,TACTILE_SWITCH_u8SWITCH4PIN
    ,TACTILE_SWITCH_u8SWITCH5PIN,TACTILE_SWITCH_u8SWITCH6PIN,TACTILE_SWITCH_u8SWITCH7PIN,TACTILE_SWITCH_u8SWITCH8PIN
    ,TACTILE_SWITCH_u8SWITCH9PIN,TACTILE_SWITCH_u8SWITCH10PIN,TACTILE_SWITCH_u8SWITCH11PIN,TACTILE_SWITCH_u8SWITCH12PIN};

const u8 TACTILE_SWITCH_u8PRESSED_STATE_ARRAY[TACTILE_SWITCH_u8SWITCHES_NUM] =
    {TACTILE_SWITCH_u8SWITCH1_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH2_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH3_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH4_PRESSED_STATE
    ,TACTILE_SWITCH_u8SWITCH5_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH6_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH7_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH8_PRESSED_STATE
    ,TACTILE_SWITCH_u8SWITCH9_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH10_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH11_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH12_PRESSED_STATE};

#elif TACTILE_SWITCH_u8SWITCHES_NUM==13

const u8 TACTILE_SWITCH_u8PIN_NUMBERS_ARRAY[TACTILE_SWITCH_u8SWITCHES_NUM] =
    {TACTILE_SWITCH_u8SWITCH1PIN,TACTILE_SWITCH_u8SWITCH2PIN,TACTILE_SWITCH_u8SWITCH3PIN,TACTILE_SWITCH_u8SWITCH4PIN
    ,TACTILE_SWITCH_u8SWITCH5PIN,TACTILE_SWITCH_u8SWITCH6PIN,TACTILE_SWITCH_u8SWITCH7PIN,TACTILE_SWITCH_u8SWITCH8PIN
    ,TACTILE_SWITCH_u8SWITCH9PIN,TACTILE_SWITCH_u8SWITCH10PIN,TACTILE_SWITCH_u8SWITCH11PIN,TACTILE_SWITCH_u8SWITCH12PIN
    ,TACTILE_SWITCH_u8SWITCH13PIN};

const u8 TACTILE_SWITCH_u8PRESSED_STATE_ARRAY[TACTILE_SWITCH_u8SWITCHES_NUM] =
    {TACTILE_SWITCH_u8SWITCH1_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH2_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH3_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH4_PRESSED_STATE
    ,TACTILE_SWITCH_u8SWITCH5_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH6_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH7_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH8_PRESSED_STATE
    ,TACTILE_SWITCH_u8SWITCH9_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH10_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH11_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH12_PRESSED_STATE
    ,TACTILE_SWITCH_u8SWITCH13_PRESSED_STATE};

#elif TACTILE_SWITCH_u8SWITCHES_NUM==14

const u8 TACTILE_SWITCH_u8PIN_NUMBERS_ARRAY[TACTILE_SWITCH_u8SWITCHES_NUM] =
    {TACTILE_SWITCH_u8SWITCH1PIN,TACTILE_SWITCH_u8SWITCH2PIN,TACTILE_SWITCH_u8SWITCH3PIN,TACTILE_SWITCH_u8SWITCH4PIN
    ,TACTILE_SWITCH_u8SWITCH5PIN,TACTILE_SWITCH_u8SWITCH6PIN,TACTILE_SWITCH_u8SWITCH7PIN,TACTILE_SWITCH_u8SWITCH8PIN
    ,TACTILE_SWITCH_u8SWITCH9PIN,TACTILE_SWITCH_u8SWITCH10PIN,TACTILE_SWITCH_u8SWITCH11PIN,TACTILE_SWITCH_u8SWITCH12PIN
    ,TACTILE_SWITCH_u8SWITCH13PIN,TACTILE_SWITCH_u8SWITCH14PIN};

const u8 TACTILE_SWITCH_u8PRESSED_STATE_ARRAY[TACTILE_SWITCH_u8SWITCHES_NUM] =
    {TACTILE_SWITCH_u8SWITCH1_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH2_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH3_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH4_PRESSED_STATE
    ,TACTILE_SWITCH_u8SWITCH5_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH6_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH7_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH8_PRESSED_STATE
    ,TACTILE_SWITCH_u8SWITCH9_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH10_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH11_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH12_PRESSED_STATE
    ,TACTILE_SWITCH_u8SWITCH13_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH14_PRESSED_STATE};

#elif TACTILE_SWITCH_u8SWITCHES_NUM==15

const u8 TACTILE_SWITCH_u8PIN_NUMBERS_ARRAY[TACTILE_SWITCH_u8SWITCHES_NUM] =
    {TACTILE_SWITCH_u8SWITCH1PIN,TACTILE_SWITCH_u8SWITCH2PIN,TACTILE_SWITCH_u8SWITCH3PIN,TACTILE_SWITCH_u8SWITCH4PIN
    ,TACTILE_SWITCH_u8SWITCH5PIN,TACTILE_SWITCH_u8SWITCH6PIN,TACTILE_SWITCH_u8SWITCH7PIN,TACTILE_SWITCH_u8SWITCH8PIN
    ,TACTILE_SWITCH_u8SWITCH9PIN,TACTILE_SWITCH_u8SWITCH10PIN,TACTILE_SWITCH_u8SWITCH11PIN,TACTILE_SWITCH_u8SWITCH12PIN
    ,TACTILE_SWITCH_u8SWITCH13PIN,TACTILE_SWITCH_u8SWITCH14PIN,TACTILE_SWITCH_u8SWITCH15PIN};

const u8 TACTILE_SWITCH_u8PRESSED_STATE_ARRAY[TACTILE_SWITCH_u8SWITCHES_NUM] =
    {TACTILE_SWITCH_u8SWITCH1_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH2_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH3_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH4_PRESSED_STATE
    ,TACTILE_SWITCH_u8SWITCH5_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH6_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH7_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH8_PRESSED_STATE
    ,TACTILE_SWITCH_u8SWITCH9_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH10_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH11_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH12_PRESSED_STATE
    ,TACTILE_SWITCH_u8SWITCH13_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH14_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH15_PRESSED_STATE};

#elif TACTILE_SWITCH_u8SWITCHES_NUM==16

const u8 TACTILE_SWITCH_u8PIN_NUMBERS_ARRAY[TACTILE_SWITCH_u8SWITCHES_NUM] =
    {TACTILE_SWITCH_u8SWITCH1PIN,TACTILE_SWITCH_u8SWITCH2PIN,TACTILE_SWITCH_u8SWITCH3PIN,TACTILE_SWITCH_u8SWITCH4PIN
    ,TACTILE_SWITCH_u8SWITCH5PIN,TACTILE_SWITCH_u8SWITCH6PIN,TACTILE_SWITCH_u8SWITCH7PIN,TACTILE_SWITCH_u8SWITCH8PIN
    ,TACTILE_SWITCH_u8SWITCH9PIN,TACTILE_SWITCH_u8SWITCH10PIN,TACTILE_SWITCH_u8SWITCH11PIN,TACTILE_SWITCH_u8SWITCH12PIN
    ,TACTILE_SWITCH_u8SWITCH13PIN,TACTILE_SWITCH_u8SWITCH14PIN,TACTILE_SWITCH_u8SWITCH15PIN,TACTILE_SWITCH_u8SWITCH16PIN};

const u8 TACTILE_SWITCH_u8PRESSED_STATE_ARRAY[TACTILE_SWITCH_u8SWITCHES_NUM] =
    {TACTILE_SWITCH_u8SWITCH1_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH2_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH3_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH4_PRESSED_STATE
    ,TACTILE_SWITCH_u8SWITCH5_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH6_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH7_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH8_PRESSED_STATE
    ,TACTILE_SWITCH_u8SWITCH9_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH10_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH11_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH12_PRESSED_STATE
    ,TACTILE_SWITCH_u8SWITCH13_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH14_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH15_PRESSED_STATE,TACTILE_SWITCH_u8SWITCH16_PRESSED_STATE};

#else

#error  "TACTILE_SWITCH_u8SWITCHES_NUM is out of range"

#endif

/******************************************************/
/*********************Functions************************/
/******************************************************/

extern void TACTILE_SWITCH_voidInit(void)
    {

    /*Comment!: initiate  Switches  unPressed */
    Tactile_Switch_u16State.Tactile_Switches = TACTILE_SWITCH_INITIAL_UNPRESSED;

    /*Comment!: initiate  Switches' flags down */
    Tactile_Switch_u16Bouncing_Flag.Tactile_Switches = TACTILE_FLAG_INITIAL_DOWN;

    return;
    }

extern u8 TACTILE_SWITCH_u8Read(u8 Copy_u8SwitchIdx, u8* Copy_u8PtrToResult)
    {
    u8 local_u8ErrorFlag;
    u8 local_u8Switch_Current_State;
    u8 local_u8Switch_Last_State;
    u8 local_u8Bouncing_Flag;
    u8 local_u8Switch_Pressed_State;

    /*Comment!: Check Switch range*/
    if (Copy_u8SwitchIdx < TACTILE_SWITCH_u8SWITCHES_NUM)

	{

	/*Comment!: Read Switch value*/
	DIO_u8ReadPinVal(TACTILE_SWITCH_u8PIN_NUMBERS_ARRAY[Copy_u8SwitchIdx], &local_u8Switch_Current_State);

	/*Comment!: Read Switch's Last State*/
	local_u8Switch_Last_State = GET_BIT(Tactile_Switch_u16State.Tactile_Switches, Copy_u8SwitchIdx);

	/*Comment!: Read Switch Bouncing Flag*/
	local_u8Bouncing_Flag = GET_BIT(Tactile_Switch_u16Bouncing_Flag.Tactile_Switches, Copy_u8SwitchIdx);

	/*Comment!: Check Switch Pressed State DIO_u8HIGH ~ DIO_u8LOW*/
	local_u8Switch_Pressed_State = TACTILE_SWITCH_u8PRESSED_STATE_ARRAY[Copy_u8SwitchIdx];

	/*Comment!: Check Bouncing Flag*/
	if (local_u8Bouncing_Flag == TACTILE_SWITCH_FLAG_UP)
	    {

	    /*Comment!: Check Last State For Switch*/
	    if (local_u8Switch_Current_State != local_u8Switch_Pressed_State)
		{

		TACTILE_SWITCH_u8PIN_UNPRESSED_COUUNTER_ARRAY[Copy_u8SwitchIdx]++;

		TACTILE_SWITCH_u8PIN_PRESSED_COUNTER_ARRAY[Copy_u8SwitchIdx] = 0;

		}

	    else if (local_u8Switch_Current_State == local_u8Switch_Pressed_State)
		{

		TACTILE_SWITCH_u8PIN_PRESSED_COUNTER_ARRAY[Copy_u8SwitchIdx]++;

		TACTILE_SWITCH_u8PIN_UNPRESSED_COUUNTER_ARRAY[Copy_u8SwitchIdx] = 0;

		}

	    else
		{

		}

	    /*Comment!: Check Any Counter reach the limit*/
	    if (TACTILE_SWITCH_u8PIN_PRESSED_COUNTER_ARRAY[Copy_u8SwitchIdx] == TACTILE_SWITCH_COUNTER_LIMIT)

		{
		/*Comment!: Reset Pressed Counter*/
		TACTILE_SWITCH_u8PIN_PRESSED_COUNTER_ARRAY[Copy_u8SwitchIdx] = 0;

		/*Comment!: Make Bouncing Flag Low*/
		CLR_BIT(Tactile_Switch_u16Bouncing_Flag.Tactile_Switches, Copy_u8SwitchIdx);

		/*Comment!: Return Switch Statues as Pressed*/
		*Copy_u8PtrToResult = TACTILE_SWITCH_u8PRESSED;

		/*Comment!: Save Switch Statues as Pressed*/
		SET_BIT(Tactile_Switch_u16State.Tactile_Switches, Copy_u8SwitchIdx);

		}

	    else if (TACTILE_SWITCH_u8PIN_UNPRESSED_COUUNTER_ARRAY[Copy_u8SwitchIdx]
		    == TACTILE_SWITCH_COUNTER_LIMIT)

		{
		/*Comment!: Reset UnPressed Counter*/
		TACTILE_SWITCH_u8PIN_UNPRESSED_COUUNTER_ARRAY[Copy_u8SwitchIdx] = 0;

		/*Comment!: Make Bouncing Flag Low*/
		CLR_BIT(Tactile_Switch_u16Bouncing_Flag.Tactile_Switches, Copy_u8SwitchIdx);

		/*Comment!: Return Switch Statues as UnPressed*/
		*Copy_u8PtrToResult = TACTILE_SWITCH_u8UNPRESSED;

		/*Comment!: Save Switch Statues as UnPressed*/
		CLR_BIT(Tactile_Switch_u16State.Tactile_Switches, Copy_u8SwitchIdx);

		}

	    else

		{
		/*Comment!: Return Switch's Last state*/
		*Copy_u8PtrToResult = local_u8Switch_Last_State;

		}

	    }

	/*Comment!: Check if code is out of bouncing state*/
	else if (local_u8Bouncing_Flag == TACTILE_SWITCH_BOUNCING_FLAG_DOWN)
	    {

	    /*Comment!: Check Switch's Last state*/
	    switch (local_u8Switch_Last_State)
		{

	    case TACTILE_SWITCH_u8UNPRESSED:

		    /*Comment!: Check if switch is pressed*/
		if (local_u8Switch_Current_State == local_u8Switch_Pressed_State)
		    {

		    /*Comment!: Rise Bouncing Flag*/
		    SET_BIT(Tactile_Switch_u16Bouncing_Flag.Tactile_Switches, Copy_u8SwitchIdx);

		    }

		else
		    {

		    }

		/*Comment!: Return Switch as UnPressed*/
		*Copy_u8PtrToResult = TACTILE_SWITCH_u8UNPRESSED;

		break;

	    case TACTILE_SWITCH_u8PRESSED:

		    /*Comment!: Check if switch is UnPressed*/
		if (local_u8Switch_Current_State != local_u8Switch_Pressed_State)
		    {

		    /*Comment!: Rise Bouncing Flag*/
		    SET_BIT(Tactile_Switch_u16Bouncing_Flag.Tactile_Switches, Copy_u8SwitchIdx);

		    }

		else
		    {

		    }

		/*Comment!: Return Switch as Pressed*/
		*Copy_u8PtrToResult = TACTILE_SWITCH_u8PRESSED;

		break;

	    default:

		break;

		}

	    }

	else
	    {

	    }

	local_u8ErrorFlag = ok;

	}

    else
	{

	local_u8ErrorFlag = error;

	}

    return local_u8ErrorFlag;
    }
